lib/yabe_web/router.ex
defmodule YabeWeb.Router do
  use YabeWeb, :router

  import YabeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {YabeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Other scopes may use custom stacks.
  scope "/api", YabeWeb do
    pipe_through :api

    resources "/items", ItemController, except: [:new, :edit]
    resources "/outside_items", OutsideItemController, except: [:new, :edit]
    resources "/sales", SaleController, except: [:new, :edit]
    resources "/outside_sales", OutsideSaleController, except: [:new, :edit]
    resources "/users", UserController, only: [:show]

    get "/sales/sold_by/:seller_id", SaleController, :show_by_seller
    get "/sales/bought_by/:buyer_id", SaleController, :show_by_buyer
    get "/outside_sales/quantity_sold/:item_id", OutsideSaleController, :show_quantity_sold
    get "/outside_sales/bought_by/:buyer_id", OutsideSaleController, :show_by_buyer
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: YabeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", YabeWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", YabeWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", YabeWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

    ## React catch-all

    scope "/", YabeWeb do
      pipe_through :browser

      get "/*path", PageController, :index
    end
end

lib/yabe_web/views/layout_view.ex
defmodule YabeWeb.LayoutView do
  use YabeWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/yabe_web/templates/layout/_user_menu.html.heex
<div class='row'>
  <div class='col-12'>
    <%= if @current_user do %>
      Logged in as: <%= @current_user.email %> (<%= @current_user.role %>)
      <div class="d-inline-block">
        <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "btn btn-primary m-2" %>
        <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "btn btn-primary m-2" %>
      </div>
    <% else %>
      <div>
        <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "btn btn-primary m-2" %>
        <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "btn btn-primary m-2" %>
      </div>
    <% end %>
  </div>
  <hr/>
</div>

lib/yabe_web/templates/layout/app.html.heex
<main class="container">
  <%= @inner_content %>
</main>

lib/yabe_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/yabe_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "Yabe", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />

    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <%= render "_user_menu.html", assigns %>
        </nav>
      </section>

      <%= if @current_user do %>
        <div hidden id="current-user">
          <div id="current-user-id"><%= @current_user.id %></div>
          <div id="current-user-email"><%= @current_user.email %></div>
          <div id="current-user-role"><%= @current_user.role %></div>
        </div>
      <% end %>
    </header>

    <%= @inner_content %>
  </body>
</html>