lib/yabe_web/router.ex
defmodule YabeWeb.Router do
  use YabeWeb, :router

  import YabeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {YabeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Other scopes may use custom stacks.
  scope "/api", YabeWeb do
    pipe_through :api

    resources "/items", ItemController, except: [:new, :edit]
    resources "/outside_items", OutsideItemController, except: [:new, :edit]
    resources "/sales", SaleController, except: [:new, :edit]
    resources "/outside_sales", OutsideSaleController, except: [:new, :edit]
    resources "/users", UserController, only: [:show]

    get "/sales/sold_by/:seller_id", SaleController, :show_by_seller
    get "/sales/bought_by/:buyer_id", SaleController, :show_by_buyer
    get "/outside_sales/quantity_sold/:item_id", OutsideSaleController, :show_quantity_sold
    get "/outside_sales/bought_by/:buyer_id", OutsideSaleController, :show_by_buyer
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: YabeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", YabeWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", YabeWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", YabeWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

    ## React catch-all

    scope "/", YabeWeb do
      pipe_through :browser

      get "/*path", PageController, :index
    end
end

lib/yabe_web/controllers/user_registration_controller.ex
defmodule YabeWeb.UserRegistrationController do
  use YabeWeb, :controller

  alias Yabe.Accounts
  alias Yabe.Accounts.User
  alias YabeWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :edit, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/yabe_web/views/user_registration_view.ex
defmodule YabeWeb.UserRegistrationView do
  use YabeWeb, :view
end

lib/yabe_web/templates/user_registration/new.html.heex
<h1>Register</h1>

<.form let={f} for={@changeset} action={Routes.user_registration_path(@conn, :create)}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :email, class: "form-label" %>
  <%= email_input f, :email, required: true, class: "form-control" %>
  <%= error_tag f, :email %>

  <%= label f, :password, class: "form-label" %>
  <%= password_input f, :password, required: true, class: "form-control" %>
  <%= error_tag f, :password %>

  <%= label f, :role, class: "form-label" %>
  <br />
  <%= label f, :role_buyer, "Buyer", class: "form-label" %>
  <%= radio_button f, :role, "buyer" %>
  <%= label f, :role_seller, "Seller", class: "form-label" %>
  <%= radio_button f, :role, "seller" %>

  <div>
    <%= submit "Register", class: "btn btn-primary" %>
  </div>
</.form>

<p>
  <%= link "Log in", to: Routes.user_session_path(@conn, :new) %> |
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
</p>